### PR TITLE
Issue with not ready result_value

### PR DESCRIPTION
**Pull request by dinosaurtirex**
If value is not ready, library returns:
```
taskiq_result: TaskiqResult[_ReturnType] = pickle.loads(result_value)
TypeError: a bytes-like object is required, not 'NoneType'
```
Now it will return real error

### CODE REVIEW

**Comment by s3rius** [comment]
Can you rebase your changes onto develop?

**Review by s3rius — APPROVED** [review]
Looks good to me. But please rebase onto develop before merging.

**Comment by dinosaurtirex** [comment]
> Looks good to me. But please rebase onto develop before merging.


> Looks good to me. But please rebase onto develop before merging.

Yea of course, sorry for bit misunderstanding by my side. i will do it tomorrow. Also i guess may be to add new exception for this case? Or built in LookupError is fine?

**Comment by s3rius** [comment]
Thank you very much. Built-in lookup should be fine.

**Comment by dinosaurtirex** [comment]
> Thank you very much. Built-in lookup should be fine.

Just check it out and see that it already implemented in develop branch, so just closing PR. Thanks for good library and your time!

**Pull request closed without merging**
